---
config:
  sankey:
    showValues: true
    width: 800
    height: 1000
    nodeAlignment: justify
    linkColor: gradient
---
sankey-beta

Codebase,Shared Code,24592
Codebase,iOS Swift App,3079
Codebase,Other,3039
Codebase,CMP Apps,2169
Codebase,Server,1528
Codebase,Screenshot Tests,983

Shared Code,presentation-feature,5730
Shared Code,viewmodel,4566
Shared Code,usecase,4073
Shared Code,data-network,2412
Shared Code,domain,2293
Shared Code,presentation-core,2095
Shared Code,data,1801
Shared Code,data-local,1059
Shared Code,ai,493
Shared Code,compose-resources,70

iOS Swift App,iosAppSwiftUI,3079

Other,buildSrc,1475
Other,test-common,609
Other,e2e-tests,271
Other,ios-swift-di,235
Other,fixtures,209
Other,presentation-model,209
Other,iosAppComposeUI,31

CMP Apps,compose-app,2169

Server,server:app,1342
Server,server:data,152
Server,server:domain,34

Screenshot Tests,android-screenshot-tests,983
