graph TD
    subgraph "iOS Apps"
        IosSwiftDi[":ios-swift-di"]
        IosAppComposeUi.xcodeproj["ios-app-compose-ui.xcodeproj"]
        IosAppSwiftUi.xcodeproj["ios-app-swift-ui.xcodeproj"]
    end

    subgraph "Compose Apps"
        ComposeApp[":compose-app"]
    end

    subgraph "Server"
        ServerApp[":server:app"]
        ServerData[":server:data"]
        ServerDomain[":server:domain"]
    end

    subgraph "Presentation"
        ComposeResources[":compose-resources"]
        PresentationCore[":presentation-core"]
        PresentationFeature[":presentation-feature"]
        PresentationModel[":presentation-model"]
        Viewmodel[":viewmodel"]
    end

    subgraph "Domain Layer"
        Ai[":ai"]
        Domain[":domain"]
        Usecase[":usecase"]
    end

    subgraph "Data Layer"
        Data[":data"]
        DataLocal[":data-local"]
        DataNetwork[":data-network"]
    end

    subgraph "Screenshot Tests"
        AndroidScreenshotTests[":android-screenshot-tests"]
    end

    subgraph "Others"
        Fixtures[":fixtures"]
    end

    %% Dependencies
    Ai --> Domain
    Ai --> PresentationModel

    AndroidScreenshotTests --> ComposeResources
    AndroidScreenshotTests --> Domain
    AndroidScreenshotTests --> PresentationCore
    AndroidScreenshotTests --> PresentationFeature
    AndroidScreenshotTests --> PresentationModel

    ComposeApp --> Ai
    ComposeApp --> ComposeResources
    ComposeApp --> Data
    ComposeApp --> PresentationCore
    ComposeApp --> PresentationFeature
    ComposeApp --> Usecase
    ComposeApp --> Viewmodel

    Data --> DataLocal
    Data --> DataNetwork
    Data --> Domain

    DataLocal --> Domain

    DataNetwork --> Domain
    DataNetwork --> Fixtures

    Fixtures --> Domain

    IosSwiftDi --> Ai
    IosSwiftDi --> Data
    IosSwiftDi --> PresentationModel
    IosSwiftDi --> Usecase
    IosSwiftDi --> Viewmodel

    PresentationCore --> ComposeResources
    PresentationCore --> Domain
    PresentationCore --> PresentationModel

    PresentationFeature --> ComposeResources
    PresentationFeature --> PresentationCore
    PresentationFeature --> PresentationModel

    PresentationModel --> Domain

    ServerApp --> Domain
    ServerApp --> ServerData
    ServerApp --> ServerDomain

    ServerData --> Domain
    ServerData --> Fixtures
    ServerData --> ServerDomain

    ServerDomain --> Domain

    Usecase --> Ai
    Usecase --> Domain
    Usecase --> PresentationModel

    Viewmodel --> PresentationModel
    Viewmodel --> Usecase

    IosAppComposeUi.xcodeproj --> ComposeApp

    IosAppSwiftUi.xcodeproj --> IosSwiftDi
