graph TD
    subgraph "iOS Apps"
        IosSwiftDi[":ios-swift-di"]
        IosAppComposeUi["ios-app-compose-ui"]
        IosAppSwiftUi["ios-app-swift-ui"]
    end

    subgraph "Compose Apps"
        ComposeApp[":compose-app"]
    end

    subgraph "Server"
        ServerApp[":server:app"]
        ServerData[":server:data"]
        ServerDomain[":server:domain"]
    end

    subgraph "Compose UI"
        UiCore[":ui-core"]
    end

    subgraph "Compose + ViewModel UI"
        UiFeature[":ui-feature"]
    end

    subgraph "Presentation Layer"
        Viewmodel[":viewmodel"]
    end

    subgraph "Domain Layer"
        Domain[":domain"]
        Usecase[":usecase"]
    end

    subgraph "Data Layer"
        Data[":data"]
        Networking[":networking"]
    end

    %% Dependencies
    ComposeApp --> Data
    ComposeApp --> Domain
    ComposeApp --> Networking
    ComposeApp --> UiCore
    ComposeApp --> UiFeature
    ComposeApp --> Usecase
    ComposeApp --> Viewmodel

    Data --> Domain
    Data --> Networking

    IosSwiftDi --> Data
    IosSwiftDi --> Domain
    IosSwiftDi --> Usecase
    IosSwiftDi --> Viewmodel

    Networking --> Domain

    ServerApp --> Domain
    ServerApp --> ServerData
    ServerApp --> ServerDomain

    ServerData --> Domain
    ServerData --> ServerDomain

    ServerDomain --> Domain

    UiCore --> Domain

    UiFeature --> Domain
    UiFeature --> UiCore

    Usecase --> Domain

    Viewmodel --> Domain
    Viewmodel --> Usecase

    IosAppComposeUi --> ComposeApp

    IosAppSwiftUi --> IosSwiftDi
